# eksctl create cluster --config-file=robot-shop-cluster.yml
# eksctl delete cluster --config-file=robot-shop-cluster.yml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: robot-shop-cluster
  region: us-east-1

managedNodeGroups:
# `instanceTypes` defaults to [`m5.large`]
- name: robot-shop-1
  ssh:
    publicKeyName: naveen-kalidindi