apiVersion: v1
kind: ConfigMap
metadata:
  namespace: robotshop
  name: payment-config
data:
  CART_HOST: cart
  USER_HOST: user
  AMQP_HOST: rabbitmq
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  namespace: robotshop
  labels:
    name: payment
    tier: App
    owner: Naveen
spec:
  containers:
  - name: payment
    image: naveen2809/payment:1.0.0
    imagePullPolicy: Always
    envFrom:
      - configMapRef:
            name: payment-config
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: robotshop
spec:
  selector:
    name: payment
    tier: App
    owner: Naveen
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080