apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    kubernetes.io/change-cause: "version 1.0"
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    # Default Behavior
    # rollingUpdate:
    #   maxUnavailable: 1 # we asked for 10, we are okay if 9 are running at the time of upgrade
    #   maxSurge: 1 # we asked for 10, we are okay at the time of upgrade 11 are running
    rollingUpdate:
      maxUnavailable: 2 # we asked for 10, we are okay if 8 are running at the time of upgrade
      maxSurge: 2 # we asked for 10, we are okay at the time of upgrade 12 are running
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

# check status of the deployment
# kubectl rollout status deployment/nginx-deployment