apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: robot-shop
  name: robot-shop-admin-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robot-shop-admin-rolebinding
  namespace: robot-shop
subjects:
- kind: User
  name: robot-shop-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: robot-shop-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
- apiGroups: ["*"]
  resources: ["nodes","namespaces","services","deployments","customresourcedefinitions"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-role-binding
subjects:
- kind: User
  name: robot-shop-admin # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io