apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: robot-shop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: robot-shop
  labels:
    name: shipping
    tier: App
    owner: Naveen
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      name: shipping
      tier: App
      owner: Naveen
  template:
    metadata:
      labels:
        name: shipping
        tier: App
        owner: Naveen
    spec:
      containers:
      - name: shipping
        imagePullPolicy: Always
        image: naveen2809/shipping:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: shipping-config
        ports:
        - containerPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: robot-shop
spec:
  selector:
    name: shipping
    tier: App
    owner: Naveen
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}