apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: robot-shop
  labels:
    name: ratings
    tier: App
    owner: Naveen
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ratings
      tier: App
      owner: Naveen
  template:
    metadata:
      labels:
        name: ratings
        tier: App
        owner: Naveen
    spec:
      containers:
      - name: ratings
        imagePullPolicy: Always
        image: naveen2809/ratings:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: robot-shop
spec:
  selector:
    name: ratings
    tier: App
    owner: Naveen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80