apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::691003562449:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-heTFny2fpKBf
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::691003562449:user/robot-shop-admin
      username: robot-shop-admin
    - userarn: arn:aws:iam::691003562449:user/naveen
      username: naveen
    - userarn: arn:aws:iam::691003562449:user/neelima
      username: neelima
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::691003562449:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-heTFny2fpKBf\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::691003562449:user/robot-shop-admin\n  username: robot-shop-admin\n- userarn: arn:aws:iam::691003562449:user/naveen\n  username: naveen\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-12-26T05:32:44Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"10428","uid":"859f2ea0-b8c3-4d95-a503-f383cf5d7760"}}
  creationTimestamp: "2023-12-26T05:32:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "37763"
  uid: 859f2ea0-b8c3-4d95-a503-f383cf5d7760