apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: robot-shop
  name: robot-shop-read-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robot-shop-read-rolebinding
  namespace: robot-shop
subjects:
- kind: User
  name: naveen
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: robot-shop-read-role
  apiGroup: rbac.authorization.k8s.io