apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: robot-shop
data:
  MONGO_URL: mongodb://mongodb:27017/catalogue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: robot-shop
  labels:
    name: catalogue
    tier: App
    owner: Naveen
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      name: catalogue
      tier: App
      owner: Naveen
  template:
    metadata:
      labels:
        name: catalogue
        tier: App
        owner: Naveen
    spec:
      containers:
      - name: catalogue
        imagePullPolicy: Always
        image: naveen2809/catalogue:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: catalogue-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: robot-shop
spec:
  selector:
    name: catalogue
    tier: App
    owner: Naveen
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}