apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: robotshop
data:
  MONGO_URL: mongodb://mongodb:27017/catalogue
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  namespace: robotshop
  labels:
    name: catalogue
    tier: App
    owner: Naveen
spec:
  containers:
  - name: catalogue
    imagePullPolicy: Always
    image: naveen2809/catalogue:1.0.0
    envFrom:
      - configMapRef:
            name: catalogue-config
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: robotshop
spec:
  selector:
    name: catalogue
    tier: App
    owner: Naveen
  ports:
  - port: 8080
    targetPort: 8080