apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: robot-shop
spec:
  selector:
    matchLabels:
      name: redis # has to match .spec.template.metadata.labels
      tier: DB
      owner: Naveen
  serviceName: "redis"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        name: redis # has to match .spec.template.metadata.labels
        tier: DB
        owner: Naveen
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: robot-shop
spec:
  clusterIP: None
  selector:
    name: redis
    tier: DB
    owner: Naveen
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis