apiVersion: v1
kind: Pod
metadata:
  name: ratings
  namespace: robotshop
  labels:
    name: ratings
    tier: App
    owner: Naveen
spec:
  containers:
  - name: ratings
    image: naveen2809/ratings:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: robotshop
spec:
  selector:
    name: ratings
    tier: App
    owner: Naveen
  ports:
  - port: 80
    targetPort: 80