apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: robot-shop
data:
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: robot-shop
  labels:
    name: user
    tier: App
    owner: Naveen
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      name: user
      tier: App
      owner: Naveen
  template:
    metadata:
      labels:
        name: user
        tier: App
        owner: Naveen
    spec:
      containers:
      - name: user
        imagePullPolicy: Always
        image: naveen2809/user:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: user-config
        ports:
        - containerPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: robot-shop
spec:
  selector:
    name: user
    tier: App
    owner: Naveen
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}