apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: robot-shop
data:
  nginx.conf: |
    # this config is loading from nginx config map
    user nginx;
    worker_processes auto;
    pid /var/run/nginx.pid;

    error_log  /var/log/nginx/error.log notice;

    events {
      worker_connections 768;
      # multi_accept on;
    }

    http {

        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr $time_local $request $status $body_bytes_sent $request_time';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;

        server {
            listen       80;
            server_name  localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }

            proxy_http_version 1.1;
            location /images/ {
            expires 5s;
            root   /usr/share/nginx/html;
            try_files $uri /images/placeholder.jpg;
            }
            
            location /api/catalogue/ {
                proxy_pass http://catalogue:8080/;
            }

            location /api/user/ {
                proxy_pass http://user:8080/;
            }  

            location /api/cart/ {
                proxy_pass http://cart:8080/;
            }

            location /api/shipping/ {
                proxy_pass http://shipping:8080/;
            }

            location /api/payment/ {
                proxy_pass http://payment:8080/;
            }  
        
            location /api/ratings/ {
                proxy_pass http://ratings:80/;
            }

            location /nginx_status {
                stub_status on;
                access_log off;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: robot-shop
  labels:
    name: web
    tier: FE
    owner: Naveen
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
      tier: FE
      owner: Naveen
  template:
    metadata:
      labels:
        name: web
        tier: FE
        owner: Naveen
    spec:
      containers:
      - name: web
        imagePullPolicy: Always
        image: naveen2809/web:2.0.1
        resources:
          requests:
            cpu: "100m"
            memory: "156Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
              name: nginx-config
              items:
                - key: nginx.conf
                  path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: robot-shop
spec:
  type: LoadBalancer
  selector:
    name: web
    tier: FE
    owner: Naveen
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: robot-shop
spec:
  scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: web
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50