apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: robot-shop
  labels:
    name: ratings
    tier: App
    owner: Naveen
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      name: ratings
      tier: App
      owner: Naveen
  template:
    metadata:
      labels:
        name: ratings
        tier: App
        owner: Naveen
    spec:
      containers:
      - name: ratings
        imagePullPolicy: Always
        image: naveen2809/ratings:{{ .Values.deployment.imageVersion }}
        ports:
        - containerPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: robot-shop
spec:
  selector:
    name: ratings
    tier: App
    owner: Naveen
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}