apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: robot-shop
data:
  CATALOGUE_HOST: "catalogue"
  REDIS_HOST: "redis"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: robot-shop
  labels:
    name: cart
    tier: App
    owner: Naveen
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      name: cart
      tier: App
      owner: Naveen
  template:
    metadata:
      labels:
        name: cart
        tier: App
        owner: Naveen
    spec:
      containers:
      - name: cart
        imagePullPolicy: Always
        image: naveen2809/cart:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: cart-config
        ports:
        - containerPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: robot-shop
spec:
  selector:
    name: cart
    tier: App
    owner: Naveen
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}