apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: robot-shop
data:
  CART_HOST: "cart"
  USER_HOST: "user"
  AMQP_HOST: "rabbitmq"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: robot-shop
  labels:
    name: payment
    tier: App
    owner: Naveen
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      name: payment
      tier: App
      owner: Naveen
  template:
    metadata:
      labels:
        name: payment
        tier: App
        owner: Naveen
    spec:
      containers:
      - name: payment
        imagePullPolicy: Always
        image: naveen2809/payment:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: payment-config
        ports:
        - containerPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: robot-shop
spec:
  selector:
    name: payment
    tier: App
    owner: Naveen
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}